### ISSUE TITLE
MSMExplorer Installation: conflict error 'numba'

### ISSUE THREAD

**Issue by AlirezaTafazzol** [msmbuilder/msmexplorer#117]
$conda install -c omnia msmexplorer
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:

   -msmexplorer
   -numba
Use "conda info " to see the dependencies for each package.

**Comment by cxhernandez** [comment]
Exactly as it says, conda can't install `msmexplorer` while the current version of `numba` is installed. You can either remove `numba` or [create a new conda environment](https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands).
