### ISSUE TITLE
What are the numbers plotted on the axis of the histogram plot

### ISSUE THREAD

**Issue by orthonalmatrix** [msmbuilder/msmexplorer#122]
I cannot find any documentation that says what the numbers given on the histogram chart when I use: plot_histogram. In the example on the website it says:  tIC1=-0.33 and two numbers super and subscripts. What do these mean?

**Comment by cxhernandez** [comment]
It comes from the `show_titles` flag: http://msmbuilder.org/msmexplorer/1.1.0/generated/msmexplorer.plot_histogram.html#msmexplorer.plot_histogram

Basically this is just the median and the interquartile range. This plot is actually borrowed from the [`corner.py`](http://corner.readthedocs.io/en/latest/index.html) package.
